### ISSUE TITLE
question about  transformer bridging layer

### ISSUE THREAD

**Issue by WANGLEKV** [vision4robotics/UDAT#1]
Hello, I'm very interested in your research. Because the datasets are too large, it is not easy to run through the code. I want to know the size of the feature extractor when it is passed into the transformer bridging layer. Does the feature size change after feature alignment？

**Comment by JayYe99** [comment]
Hi, thank you for your interest. The dimensions of features input into the transformer layer are 7x7x256 for the template branch and 31x31x256 for the search branch. The feature size will not change during the feature alignment.
