### ISSUE TITLE
难以复现您的结果

### ISSUE THREAD

**Issue by Air1000thsummer** [vision4robotics/UDAT#12]
尝试复现您的结果，但未能得到满意的效果，不知是否是复现步骤的问题，如果可以的话，请提供详细的复现步骤。

**Comment by Jay-Ye** [comment]
I cannot comment without any details. Could you state your question more clearly?

**Comment by Air1000thsummer** [comment]
Can I ask you a question, for some reason, when I tried to generate the target boxes in the preprocessing step, most of the target boxes fetched in the first video 0000box1 were Nan.

**Comment by Jay-Ye** [comment]
Please see https://github.com/vision4robotics/UDAT/issues/2.
