### ISSUE TITLE
The code of t-SNE in Figure 4 

### ISSUE THREAD

**Issue by xyl-507** [vision4robotics/UDAT#5]
Dear author, thank you very much for your work. 
I wonder if the t-SNE code used in Figure 4 will be made public?
This visualization method is very interesting!
Thanks in advance!

![t-SNE for Unsupervised Domain Adaptation for Nighttime Aerial Tracking](https://user-images.githubusercontent.com/69385203/201114959-655bd101-acb0-4e8e-b4bf-509892f85116.jpg)

**Comment by JayYe99** [comment]
Thank you for your interest in this work. The feature visualization is generated by t-SNE, the base code of which can be found at https://opentsne.readthedocs.io/en/latest/index.html. Please kindly check and modify it accordingly.

**Comment by xyl-507** [comment]
It's helpful! Thanks!
