### ISSUE TITLE
请问三个数据集的att文件夹中对应的Attributes顺序是怎么排列的

### ISSUE THREAD

**Issue by kongbia** [vision4robotics/UDAT#8]

**Comment by kongbia** [comment]
另外原始的UAVDark70似乎并没有论文图8中的Low ambient intensity属性，请问是否需要更新增加该属性

**Comment by JayYe99** [comment]
Hi, for NAT2021 and NAT2021L, the order of attributes in the annotation file is 'Aspect ratio change' 'Background clutter' 'Camera motion'  'Fast motion' 'Full occlusion'  'Illumination variation' 'Low ambient intensity' 'Out-of-view'  'Partial occlusion'  'Scale variation' 'Similar object' 'Viewpoint change'.
For UAVDark70, the order is 'Viewpoint change' 'Fast motion' 'Low resolution' 'Occlusion' 'Illumination variation'.

The annotation of the low ambient intensity (LAI) attribute of UAVDark70 is uploaded [here](https://github.com/vision4robotics/UDAT/tree/main/raw_results/UAVDark70_att_LAI).

**Comment by kongbia** [comment]
> Hi, for NAT2021 and NAT2021L, the order of attributes in the annotation file is 'Aspect ratio change' 'Background clutter' 'Camera motion' 'Fast motion' 'Full occlusion' 'Illumination variation' 'Low ambient intensity' 'Out-of-view' 'Partial occlusion' 'Scale variation' 'Similar object' 'Viewpoint change'. For UAVDark70, the order is 'Viewpoint change' 'Fast motion' 'Low resolution' 'Occlusion' 'Illumination variation'.
> 
> The annotation of the low ambient intensity (LAI) attribute of UAVDark70 is uploaded [here](https://github.com/vision4robotics/UDAT/tree/main/raw_results/UAVDark70_att_LAI).

非常感谢！
