### ISSUE TITLE
About the implementation details of Figure 4 in the paper

### ISSUE THREAD

**Issue by blackight** [vision4robotics/UDAT#9]
Hi,I have some questions about this paper.
Figure 4 in the paper reports the t-SNE results of the features before and after the Bridging layer. I want to know whether the t-SNE input here is the feature of the domain transformer discriminator or the original feature directly output by the Bridging layer. If so, does the feature output by the Feature extractor before the Bridging layer need to train an additional domain discriminator.
Thank you!
![image](https://user-images.githubusercontent.com/40955241/220858376-4622d830-d763-4fb8-a302-9fb2a2cc067d.png)

**Comment by JayYe99** [comment]
Hi, thanks for your question. The features visualized are all the direct output of the feature extractor or bridging layer. About your suggestion, I would say it is also worth trying. In this work, we attempt to bridge the domain gap at the feature level. In fact, you can further try to bridge the domain gap at the image level, similarity map level, and classification&regression map level.

**Comment by blackight** [comment]
Thank you for your reply. 
It seems that all the points are extracted from these two pictures. Before, I thought that the distribution of data in this picture was collected from the entire dataset. Thank you very much for your explanation.

**Comment by Jay-Ye** [comment]
Good to know. I apologize for the misleading.
All the best.
